version: "3.8"
services:
  database:
    image: postgres:latest
    container_name: database-psql
    ports:
      - 5433:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    volumes:
    - ./pg_data:/var/lib/postgresql/data/pgdata
  server:
    depends_on:
      - database
    restart: always
    build: .
    container_name: server-container
    environment:
     - DB_HOST=database-psql
     - DB_PORT=5432
     - DB_NAME=postgres
     - DB_USERNAME=postgres
     - DB_PASSWORD=root
    expose:
      - 8080
    links:
      - database