version: "3.8"
services:
  database:
    image: postgres:latest
    container_name: news-manager-database
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    restart: always
  server:
    depends_on:
      - database
    links:
      - database
    image: artscactus/news-manager:latest
    restart: on-failure
    container_name: news-manager-server
    environment:
     - SPRING_DATASOURCE_URL=jdbc:postgresql://database/postgres
     - SPRING_DATASOURCE_USERNAME=postgres
     - SPRING_DATASOURCE_PASSWORD=root
    ports:
    - 8080:8080
    expose:
      - 8080
